[package]
name = "websocket"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26"
tower = "0.5"
